In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("D:/Porto Magang/Used-car-price-prediction/data/used_car.csv")
df

,car name,brand,year,mileage (km),location,transmission,plate type,rear camera,sun roof,auto retract mirror,electric parking brake,map navigator,vehicle stability control,keyless push start,sports mode,360 camera view,power sliding door,auto cruise control,price (Rp),instalment (Rp|Monthly)
0,AYLA X 1.2,Daihatsu,2018,10.508,Jakarta Utara,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,101000000,2060000
1,AGYA TRD SPORTIVO 1.0,Toyota,2015,112.888,Bogor,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,82000000,1670000
2,X-TRAIL 2.5,Nissan,2015,118.429,Surabaya,Automatic,odd plate,0,0,0,0,0,0,1,0,1,0,0,169000000,3440000
3,YARIS S TRD 1.5,Toyota,2020,15.945,Tangerang Selatan,Automatic,odd plate,0,0,0,0,0,0,0,0,0,0,0,218000000,4440000
4,AGYA G 1.2,Toyota,2019,30.404,Jakarta Barat,Manual,odd plate,0,0,0,0,0,0,0,0,0,0,0,117000000,2380000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,RAIZE GR SPORT TSS 1.0,Toyota,2021,32.288,Bogor,Automatic,odd plate,0,0,1,0,0,0,0,0,0,0,0,234000000,4770000
605,AGYA G TRD 1.2,Toyota,2019,26.474,Jakarta Utara,Automatic,odd plate,0,0,0,0,0,0,0,0,0,0,0,136000000,2770000
606,STARGAZER PRIME 1.5,Hyundai,2022,2.651,Bogor,Automatic,even plate,0,0,1,0,0,0,0,0,0,0,0,246000000,5010000
607,CALYA G 1.2,Toyota,2017,34.349,Jakarta Utara,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,116000000,2360000
608,XENIA R SPORTY 1.3,Daihatsu,2017,90.740,Bogor,Manual,even plate,1,0,0,0,0,0,0,0,0,0,0,149000000,3040000

In [14]:
df.head(5)

,car name,brand,year,mileage (km),location,transmission,plate type,rear camera,sun roof,auto retract mirror,electric parking brake,map navigator,vehicle stability control,keyless push start,sports mode,360 camera view,power sliding door,auto cruise control,price (Rp),instalment (Rp|Monthly)
0,AYLA X 1.2,Daihatsu,2018,10.508,Jakarta Utara,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,101000000,2060000
1,AGYA TRD SPORTIVO 1.0,Toyota,2015,112.888,Bogor,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,82000000,1670000
2,X-TRAIL 2.5,Nissan,2015,118.429,Surabaya,Automatic,odd plate,0,0,0,0,0,0,1,0,1,0,0,169000000,3440000
3,YARIS S TRD 1.5,Toyota,2020,15.945,Tangerang Selatan,Automatic,odd plate,0,0,0,0,0,0,0,0,0,0,0,218000000,4440000
4,AGYA G 1.2,Toyota,2019,30.404,Jakarta Barat,Manual,odd plate,0,0,0,0,0,0,0,0,0,0,0,117000000,2380000

In [15]:
df.tail(5)

,car name,brand,year,mileage (km),location,transmission,plate type,rear camera,sun roof,auto retract mirror,electric parking brake,map navigator,vehicle stability control,keyless push start,sports mode,360 camera view,power sliding door,auto cruise control,price (Rp),instalment (Rp|Monthly)
604,RAIZE GR SPORT TSS 1.0,Toyota,2021,32.288,Bogor,Automatic,odd plate,0,0,1,0,0,0,0,0,0,0,0,234000000,4770000
605,AGYA G TRD 1.2,Toyota,2019,26.474,Jakarta Utara,Automatic,odd plate,0,0,0,0,0,0,0,0,0,0,0,136000000,2770000
606,STARGAZER PRIME 1.5,Hyundai,2022,2.651,Bogor,Automatic,even plate,0,0,1,0,0,0,0,0,0,0,0,246000000,5010000
607,CALYA G 1.2,Toyota,2017,34.349,Jakarta Utara,Manual,even plate,0,0,0,0,0,0,0,0,0,0,0,116000000,2360000
608,XENIA R SPORTY 1.3,Daihatsu,2017,90.740,Bogor,Manual,even plate,1,0,0,0,0,0,0,0,0,0,0,149000000,3040000

In [16]:
df.info

<bound method DataFrame.info of                    car name     brand  year  mileage (km)           location  \
0                AYLA X 1.2  Daihatsu  2018        10.508      Jakarta Utara
1     AGYA TRD SPORTIVO 1.0    Toyota  2015       112.888              Bogor
2               X-TRAIL 2.5    Nissan  2015       118.429           Surabaya
3           YARIS S TRD 1.5    Toyota  2020        15.945  Tangerang Selatan
4                AGYA G 1.2    Toyota  2019        30.404      Jakarta Barat
..                      ...       ...   ...           ...                ...
604  RAIZE GR SPORT TSS 1.0    Toyota  2021        32.288              Bogor
605          AGYA G TRD 1.2    Toyota  2019        26.474      Jakarta Utara
606     STARGAZER PRIME 1.5   Hyundai  2022         2.651              Bogor
607             CALYA G 1.2    Toyota  2017        34.349      Jakarta Utara
608      XENIA R SPORTY 1.3  Daihatsu  2017        90.740              Bogor

    transmission  plate type  rear camera  sun roof  auto retract mirror  \
0         Manual  even plate            0         0                    0
1         Manual  even plate            0         0                    0
2      Automatic   odd plate            0         0                    0
3      Automatic   odd plate            0         0                    0
4         Manual   odd plate            0         0                    0
..           ...         ...          ...       ...                  ...
604    Automatic   odd plate            0         0                    1
605    Automatic   odd plate            0         0                    0
606    Automatic  even plate            0         0                    1
607       Manual  even plate            0         0                    0
608       Manual  even plate            1         0                    0

     electric parking brake  map navigator  vehicle stability control  \
0                         0              0                          0
1                         0              0                          0
2                         0              0                          0
3                         0              0                          0
4                         0              0                          0
..                      ...            ...                        ...
604                       0              0                          0
605                       0              0                          0
606                       0              0                          0
607                       0              0                          0
608                       0              0                          0

     keyless push start  sports mode  360 camera view  power sliding door  \
0                     0            0                0                   0
1                     0            0                0                   0
2                     1            0                1                   0
3                     0            0                0                   0
4                     0            0                0                   0
..                  ...          ...              ...                 ...
604                   0            0                0                   0
605                   0            0                0                   0
606                   0            0                0                   0
607                   0            0                0                   0
608                   0            0                0                   0

     auto cruise control  price (Rp)  instalment (Rp|Monthly)
0                      0   101000000                  2060000
1                      0    82000000                  1670000
2                      0   169000000                  3440000
3                      0   218000000                  4440000
4                      0   117000000                  2380000
..                   ...         ...                      ...
604                    0   234000000                  4770000
605                    0   136000000                  2770000
606                    0   246000000                  5010000
607                    0   116000000                  2360000
608                    0   149000000                  3040000

[609 rows x 20 columns]>

In [17]:
df.describe

<bound method NDFrame.describe of                    car name     brand  year  mileage (km)           location  \
0                AYLA X 1.2  Daihatsu  2018        10.508      Jakarta Utara
1     AGYA TRD SPORTIVO 1.0    Toyota  2015       112.888              Bogor
2               X-TRAIL 2.5    Nissan  2015       118.429           Surabaya
3           YARIS S TRD 1.5    Toyota  2020        15.945  Tangerang Selatan
4                AGYA G 1.2    Toyota  2019        30.404      Jakarta Barat
..                      ...       ...   ...           ...                ...
604  RAIZE GR SPORT TSS 1.0    Toyota  2021        32.288              Bogor
605          AGYA G TRD 1.2    Toyota  2019        26.474      Jakarta Utara
606     STARGAZER PRIME 1.5   Hyundai  2022         2.651              Bogor
607             CALYA G 1.2    Toyota  2017        34.349      Jakarta Utara
608      XENIA R SPORTY 1.3  Daihatsu  2017        90.740              Bogor

    transmission  plate type  rear camera  sun roof  auto retract mirror  \
0         Manual  even plate            0         0                    0
1         Manual  even plate            0         0                    0
2      Automatic   odd plate            0         0                    0
3      Automatic   odd plate            0         0                    0
4         Manual   odd plate            0         0                    0
..           ...         ...          ...       ...                  ...
604    Automatic   odd plate            0         0                    1
605    Automatic   odd plate            0         0                    0
606    Automatic  even plate            0         0                    1
607       Manual  even plate            0         0                    0
608       Manual  even plate            1         0                    0

     electric parking brake  map navigator  vehicle stability control  \
0                         0              0                          0
1                         0              0                          0
2                         0              0                          0
3                         0              0                          0
4                         0              0                          0
..                      ...            ...                        ...
604                       0              0                          0
605                       0              0                          0
606                       0              0                          0
607                       0              0                          0
608                       0              0                          0

     keyless push start  sports mode  360 camera view  power sliding door  \
0                     0            0                0                   0
1                     0            0                0                   0
2                     1            0                1                   0
3                     0            0                0                   0
4                     0            0                0                   0
..                  ...          ...              ...                 ...
604                   0            0                0                   0
605                   0            0                0                   0
606                   0            0                0                   0
607                   0            0                0                   0
608                   0            0                0                   0

     auto cruise control  price (Rp)  instalment (Rp|Monthly)
0                      0   101000000                  2060000
1                      0    82000000                  1670000
2                      0   169000000                  3440000
3                      0   218000000                  4440000
4                      0   117000000                  2380000
..                   ...         ...                      ...
604                    0   234000000                  4770000
605                    0   136000000                  2770000
606                    0   246000000                  5010000
607                    0   116000000                  2360000
608                    0   149000000                  3040000

[609 rows x 20 columns]>

In [18]:
df.shape

(609, 20)

In [19]:
df.isna().sum()

car name                     0
brand                        0
year                         0
mileage (km)                 0
location                     0
transmission                 0
plate type                   0
rear camera                  0
sun roof                     0
auto retract mirror          0
electric parking brake       0
map navigator                0
vehicle stability control    0
keyless push start           0
sports mode                  0
360 camera view              0
power sliding door           0
auto cruise control          0
price (Rp)                   0
instalment (Rp|Monthly)      0
dtype: int64

In [20]:
df.duplicated().sum()

0